### ISSUE TITLE
Type TemplateComponent is part of the declarations of 2 modules

### ISSUE THREAD

**Issue by iamchairs** [patrikx3/angular-compile#11]
I'm trying to hot-swap between templates but when I do I get this error-

> Type TemplateComponent is part of the declarations of 2 modules: TemplateModule and TemplateModule! Please consider moving TemplateComponent to a higher module that imports TemplateModule and TemplateModule. You can also create a new NgModule that exports and includes TemplateComponent then import that NgModule in TemplateModule and TemplateModule.

My code-

```
<div *ngIf="viewData && model"
           [p3x-compile]="viewData"
           [p3x-compile-ctx]="this"></div>

public ngOnChanges(changes: SimpleChanges) {
    this.viewData = null;

    this._http.get(this.viewPath)
      .toPromise()
      .then((results) => {
        this.viewData = results.text();
      });
}
```

How can I avoid this error when swapping templates?

**Comment by JonasGutermuth** [comment]
I think the problem is not the swapping. I would guess you get the same error if you use the content of results.text(); directly. 
```
public ngOnChanges(changes: SimpleChanges) {
    this.viewData = "here content of your file";
```
The problem should be in the import of the TemplateModule

**Comment by JonasGutermuth** [comment]
I would guess the same. Let's wait for further information or a plunker

**Comment by iamchairs** [comment]
I've discovered how to reproduce this.

Here is my module import:

```
CompileModule.forRoot({
      module: {
        schemas: [CUSTOM_ELEMENTS_SCHEMA],
        declarations: []
      }
    })
```

Removing `declarations: []` makes the problem go away.
Not sure if this is a bug. I really don't know what declarations does.
