### ISSUE TITLE
Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by frohrka** [patrikx3/angular-compile#14]
Hi,
I've implemented your code like you described. If I run angular in dev mode everything works fine but if I build my application with with angular-cli ant -prod flag I'm getting this issue:

Error: Unexpected value 'l' imported by the module 'e'. Please add a @NgModule annotation. at y (vendor.f664917a257bc95f035a.bundle.js:1) at vendor.f664917a257bc95f035a.bundle.js:1 at Array.forEach (<anonymous>) at e.getNgModuleMetadata (vendor.f664917a257bc95f035a.bundle.js:1) at e._loadModules (vendor.f664917a257bc95f035a.bundle.js:1) at e._compileModuleAndAllComponents (vendor.f664917a257bc95f035a.bundle.js:1) at e.compileModuleAndAllComponentsAsync (vendor.f664917a257bc95f035a.bundle.js:1) at e.<anonymous> (vendor.f664917a257bc95f035a.bundle.js:1) at i (vendor.f664917a257bc95f035a.bundle.js:1) at Object.next (vendor.f664917a257bc95f035a.bundle.js:1)

Example: http://plnkr.co/edit/XZRpmaTRbh6iEwXpFuLN?p=preview

**Comment by JonasGutermuth** [comment]
The command in angular-cli for disabling aot is: 
```ng build --prod --aot=false is working.```
With this command I can use --prod in Angular-cli
