### ISSUE TITLE
Cannot use ngModel on an input in template

### ISSUE THREAD

**Issue by RhinoLance** [patrikx3/angular-compile#21]
While my template works fine normally, as soon as I add an input with an ngModel attribute, it fails with:
```text
Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'input'. ("
		<input type="text" [ERROR ->][(ngModel)]="context.name"/>
		"): ng:///RuntimeComponentModule/DynamicComponent.html@1:21
```

```javascript
//This works
let myTemplate = '<input type="text" [value]="context.name"/>';
//This doesn't
let myTemplate = '<input type="text" [(ngModel)]="context.name"/>';
```

This is how I've added the directive.  Note that the inclusion of the imports attribute makes no difference:
```html
<div 
  [p3x-compile]="myTemplate" 
  [p3x-compile-ctx]="this" 
  [p3x-compile-error-handler]="onError" 
  [p3x-compile-imports]="FormsModule"
></div>
```

There is no problem if I use the exact same HTML snippet in my normal html file, outside of the p3x directive.  Any ideas?

**Comment by manjurulcis** [comment]
Probably you didnt import the reactive forms module in your app.module.ts.

**Comment by RhinoLance** [comment]
I'm afraid I'm getting no joy.  When I try including the modules as shown below, the modules are undefined in the angular compiler.  The error message is "Unexpected value 'undefined' imported by the module 'RuntimeComponentModule'"  Any ideas?

I have included both FormsModule and ReactiveFormsModule in my app's module imports.

This is in my html:
```html
<div 
	[p3x-compile]="myTemplate" 
	[p3x-compile-ctx]="this" 
	[p3x-compile-error-handler]="onError" 
	[p3x-compile-imports]="[FormsModule, ReactiveFormsModule]"
	>
</div>
```

**Comment by RhinoLance** [comment]
If you can point me in the general direction, and provide a comment as to what you think the issue is, I'm happy to see if I can resolve it and issue a pull request once done.

**Comment by RhinoLance** [comment]
Thanks :)
