### ISSUE TITLE
Error: Runtime compiler is not loaded

### ISSUE THREAD

**Issue by RomanGalochkin** [patrikx3/angular-compile#22]
There is an Error: Runtime compiler is not loaded. When uses Angular 5.x + Angular Universal

**Comment by GalochkinKirov** [comment]
Yes. But I have solved this issue by passing compile constants in the providers. Thanks.

**Comment by zubinraja** [comment]
@RomanGalochkin could you please guide which compile constants needs to be passed to providers? also did you got it working?
