### ISSUE TITLE
NgModule 'RuntimeComponentModule' is not a subtype of 'NgModuleType'.

### ISSUE THREAD

**Issue by apocheau** [patrikx3/angular-compile#41]
I updated my project to Angular 12.2.6 and p3x-angular-compile to 2021.10.118.
When accessing the view with P3X Angular Compile, i have this error:
![Capture d’écran de 2021-09-20 16-01-51](https://user-images.githubusercontent.com/1315626/134015698-0f6968c3-8343-496c-b6e9-780babc4d635.png)

I found it is related to this part of the lib's code:
![Capture d’écran de 2021-09-20 16-50-51](https://user-images.githubusercontent.com/1315626/134023434-8a5129d3-e76e-4431-92dd-0ef9d5073b4c.png)
I searched for this error and it seems to be related to the module creation.

Although I have this error, I did not reproduced it in your demo project... I don't know if it's a particular case or if it is a mistake in my project.

Thank you for your help (and awesome lib)

**Comment by apocheau-metathinker** [comment]
Thank you so much for your reactivity.
I imported the two files (made some fixes due to strict mode and tslint) and imported CompileModule in my app.module.ts.
I still have a problem because DynamicComponent (in createNewComponent) is not imported in a module... of course it isn't since it is dynamic... but i don't know how to get ride of that.

**Comment by apocheau** [comment]
wrong account, re-posting my previous message:
Thank you so much for your reactivity.
I imported the two files (made some fixes due to strict mode and tslint) and imported CompileModule in my app.module.ts.
I still have a problem because DynamicComponent (in createNewComponent) is not imported in a module... of course it isn't since it is dynamic... but i don't know how to get ride of that.

**Comment by apocheau** [comment]
Importing the lib as you do is working. Thank you for your support.
It is sad to see that something that was trivial in AngularJs is becoming more and more difficult in Angular while this is an awesome feature.
Do you think, in future version of Angular, it will become easier or still the compiler will not be "made for that" ?
