### ISSUE TITLE
Ionic 3 support

### ISSUE THREAD

**Issue by hadrien-toma** [patrikx3/angular-compile#6]
This issue just asks for some information on a use case of this package.
@patrikx3, do you think this package could work in an Ionic 3 application?

**Comment by patrikx3** [comment]
when i have time, i support you.

**Comment by patrikx3** [comment]
if you want aot, it is a different issue, i do it but not out of the box.
i use ```corifeus-builder-angular```

**Comment by patrikx3** [comment]
of course it works with it.

**Comment by hadrien-toma** [comment]
I don't reach to get it working, there surely be something somewhere that I missed. May I ask you the steps that I have to do from a basic Ionic application (I suggest from the `blank` template: `ionic start ionic start angular-compile-ionic-test blank`?) in order to build a very simple Ionic application running your package?

**Comment by patrikx3** [comment]
ok, i will check it out, when i get a chance, it is a long weekend, ciao! but i will found it out for you.

**Comment by hadrien-toma** [comment]
It is finally working by replacing `Object.keys(cache).includes(cacheKey)` with `Object.keys(cache).indexOf(cacheKey) > -1` in the `createFactory` function.
Do you want me to do a pull request or you have a better way to fix the unsupported `includes` function?

**Comment by patrikx3** [comment]
ahh, ionic dos t support es2016, es2017? cant you turn on?

**Comment by patrikx3** [comment]
you can update your npm.
i removed es2016, es2017 support. you can use it.

**Comment by hadrien-toma** [comment]
It seems that the `target` requires es5 for the moment. Build fails for `es6` and newers.

Thank you for paying attention and being so reactive!

**Comment by patrikx3** [comment]
ciao
